[package]
name = "egg-unify"
version = "0.1.0"
edition = "2021"

[lib]
# crate-type = ["staticlib"]
crate-type = ["lib", "cdylib"]

[dependencies]
egg = "0.10"
libc = "0.2"
rand = "0.9.2"

[features]
dot = []
